using System.Collections.Generic;
using System.Text.Json;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Server;
using Beamable.SuiFederation.Endpoints;
using Beamable.SuiFederation.Features.Accounts;
using Beamable.SuiFederation.Features.Common;
using Beamable.SuiFederation.Features.Enoki;
using Beamable.SuiFederation.Features.OAuthProvider;
using Beamable.SuiFederation.Features.OAuthProvider.Exceptions;
using Beamable.SuiFederation.Features.OAuthProvider.Models;
using SuiFederationCommon;
using ChallengeSolution = Beamable.Common.Api.Auth.ChallengeSolution;

namespace Beamable.SuiFederation;

public partial class SuiFederation : IFederatedInventory<SuiEnokiIdentity>
{
    async Promise<FederatedAuthenticationResponse> IFederatedLogin<SuiEnokiIdentity>.Authenticate(string token, string challenge, string solution)
    {
        ProjectInfo.Initialize(Context.Cid, Context.Pid);
        return await Provider.GetService<AuthenticateEnokiEndpoint>()
            .Authenticate(token, challenge, solution);
    }

    Promise<FederatedInventoryProxyState> IFederatedInventory<SuiEnokiIdentity>.GetInventoryState(string id)
    {
        return new Promise<FederatedInventoryProxyState>();
    }

    Promise<FederatedInventoryProxyState> IFederatedInventory<SuiEnokiIdentity>.StartInventoryTransaction(string id, string transaction, Dictionary<string, long> currencies, List<FederatedItemCreateRequest> newItems, List<FederatedItemDeleteRequest> deleteItems,
        List<FederatedItemUpdateRequest> updateItems)
    {
        return new Promise<FederatedInventoryProxyState>();
    }

    [Callable]
    public async Promise<CommonResponse> OAuthCallback()
    {
        return await Provider.GetService<OAuthProviderCallbackService>().ProcessCallback(Context.Body);
    }


    [Callable]
    public async Promise<string> Test()
    {
        var address = await Provider.GetService<EnokiService>().GetAddress(
            "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhlOGZjOGU1NTZmN2E3NmQwOGQzNTgyOWQ2ZjkwYWUyZTEyY2ZkMGQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI4MjIwNjUxMzUyNzYtNmlxdDRia3RwYjBicGZndmE0NG81cWRtaTQ2aHMxdGUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI4MjIwNjUxMzUyNzYtNmlxdDRia3RwYjBicGZndmE0NG81cWRtaTQ2aHMxdGUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTMxNjA5MDU1NzAzODgxOTAwMjAiLCJub25jZSI6IlhiRzFGOFF5X1VCc3pDa3Z6QTBOajRXNFowdyIsIm5iZiI6MTc1MjA3NjI0NywiaWF0IjoxNzUyMDc2NTQ3LCJleHAiOjE3NTIwODAxNDcsImp0aSI6ImNmZmE5YzkxMmVhMjVjMzcwYjE3MTNmOTVhZmQyZTQ1MmJlNWFlMmEifQ.mhAs-JBsgQl1miWGx9wobYe0wFrqWAyeSeBtpJNdYdDDIUtnQTsG5_3qIh_k54vnz3Bs0e2IU1ydHjYaSqTyQ_jsrrdSvqVkzjK-7l3EWEZudVgZhLb2xN9NrlpPiYt1W2WHiJtx9mV4jju8cHyyQlm-kiDMoO2pH7a2qul37NV_uq-L11CmRshXBCORl3fWdyx1JKHHA_5jmM7vzqjSN1q-2hxVaw154xLYHH7_0h0X-M4f70skNj9xapUaQVc0JvShJDMcrr9SlAat_TU8w-q7fQBlYA2Bf1NUQikWmtf5ey5WCRs1s0vOm-Wu5EOpbq7PDgP65cWQ9IZvLr4jPQ");


        return address.Data.Address;
    }
}