using Beamable.Api.Autogenerated.Models;

namespace Beamable.SuiFederation.Extensions;

public static class CommonResponseExtensions
{
    public static CommonResponse OkResult()
    {
        return new CommonResponse
        {
            result = "ok",
        };
    }

    public static CommonResponse FailedResult()
    {
        return new CommonResponse
        {
            result = "failed",
        };
    }
}