using System.Collections.Generic;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common;
using Beamable.Common.Api.Inventory;
using Beamable.Server;
using Beamable.SuiFederation.Endpoints;
using Beamable.SuiFederation.Features.OAuthProvider;
using SuiFederationCommon;

namespace Beamable.SuiFederation;

public partial class SuiFederation : IFederatedInventory<SuiWeb3EnokiIdentity>
{
    async Promise<FederatedAuthenticationResponse> IFederatedLogin<SuiWeb3EnokiIdentity>.Authenticate(string token, string challenge, string solution)
    {
        return await Provider.GetService<AuthenticateEnokiEndpoint>()
            .Authenticate(token, challenge, solution);
    }

    Promise<FederatedInventoryProxyState> IFederatedInventory<SuiWeb3EnokiIdentity>.GetInventoryState(string id)
    {
        return new Promise<FederatedInventoryProxyState>();
    }

    Promise<FederatedInventoryProxyState> IFederatedInventory<SuiWeb3EnokiIdentity>.StartInventoryTransaction(string id, string transaction, Dictionary<string, long> currencies, List<FederatedItemCreateRequest> newItems, List<FederatedItemDeleteRequest> deleteItems,
        List<FederatedItemUpdateRequest> updateItems)
    {
        return new Promise<FederatedInventoryProxyState>();
    }

    [Callable]
    public async Promise<CommonResponse> OAuthCallback()
    {
        return await Provider.GetService<OAuthProviderCallbackService>().ProcessCallback(Context.Body);
    }
}